site_name: ED2 Documentation
repo_url: https://github.com/QS-Cube/ED2

theme:
  name: material

docs_dir: docs

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
      smart_dollar: true
      
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
  - User Guide:
      - Input format: user-guide/input-format.md
      - Outputs: user-guide/outputs.md
  - Examples:
      - Chain: examples/chain.md
      - J1â€“J2 chain: examples/j1j2_chain.md
      - Mixed-spin chain: examples/mixed_spin_chain.md
      - Square lattice: examples/square.md
      - Triangular lattice: examples/triangular.md
      - Honeycomb lattice: examples/honeycomb.md
      - Kagome lattice: examples/kagome.md
      - Cubic lattice: examples/cubic.md
      - Cubic (sp_HB): examples/cubic_sp_HB.md      
  - Validation & Performance:
      - Validation: vp/validation.md
      - Performance: vp/performance.md
  - Theory / Algorithms:
      - Overview: theory/algorithms.md
  - Reference:
      - Citation & Versioning: reference/citation-versioning.md      
